server:
  port: 80
spring:
  application:
    name: cloud-consumer-order
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
        health-check-tls-skip-verify: true
      host: 192.168.137.134
      port: 8500