server:
  port: 7001
eureka:
  server:
    enable-self-preservation: true #是否开启自我保护机制
  instance:
    hostname: eureka7001
    lease-renewal-interval-in-seconds: 30  #单位为秒(默认是30秒)
    lease-expiration-duration-in-seconds: 90  #单位为秒(默认是90秒)，超时剔除微服务
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
#    service-url:
#      defaultZone: http://localhost:7002/eureka/